netty:
  server:
    port: 8888
    ip: 127.0.0.1
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/chatserver?characterEncoding=utf-8&useSSL=false
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    use-generated-keys: true